package com.tiy;

import javax.persistence.*;

/**
 * Created by DTG2 on 09/15/16.
 */
@Entity
@Table(name = "games") //Will be  link between the Table object and a game column
public class Game {
    @Id
    @GeneratedValue //Will be a value generated by the table
    int id;

    @ManyToOne //(optional = false) //from the game's perspective
    User user;

    @Column(nullable = false) //means this column is NOT nullable. It HAS to have a name
    String name;

    @Column(nullable = false)
    String platform;

    @Column(nullable = false)
    String genre;

    @Column(nullable = false)
    int releaseYear;

    public Game() {
    }

    public Game(String name, String platform, String genre, int releaseYear, User user) {
        this.name = name;
        this.platform = platform;
        this.genre = genre;
        this.releaseYear = releaseYear;
        this.user = user;
    }
}
